export enum BotTag {
  'Anime' = 'anime',
  'Dashboard' = 'dashboard',
  'Diversão' = 'diversao',
  'Utilidades' = 'utilidades',
  'Social' = 'social',
  'Jogos' = 'jogos',
  'Música' = 'musica',
  'Moderação' = 'moderacao',
  'Economia' = 'economia',
  'NSFW' = 'nsfw',
  'Outros' = 'outros'
}

export enum BotLibrary {
  'discord.js' = 'discord.js',
  'discord.py' = 'discord.py',
  'discordCr' = 'discordCr',
  'discord.io' = 'discord.io',
  'eris' = 'eris',
  'RestCord' = 'RestCord',
  'discordia' = 'discordia',
  'nxy' = 'nxy',
  'serenity' = 'serenity',
  'discordie' = 'discordie',
  'DiscordPHP' = 'DiscordPHP',
  'Sword' = 'Sword',
  'DiscordUnity' = 'DiscordUnity',
  'litcord' = 'litcord',
  'discord-hs' = 'discord-hs',
  'discordrb' = 'discordrb',
  'Discord.Net' = 'Discord.Net',
  'JDA' = 'JDA',
  'Javacord' = 'Javacord',
  'DSharpPlus' = 'DSharpPlus',
  'dscord' = 'dscord',
  'DiscordGo' = 'DiscordGo',
  'DisGord' = 'DisGord',
  'Discord4j' = 'Discord4j',
  'discordnim' = 'discordnim',
  'Yasmin' = 'Yasmin',
  'Disco' = 'disco',
  'AckCord' = 'AckCord',
  'Bot Designer' = 'Bot Designer',
  'DBM' = 'DBM',
  'Outro' = 'Outro'
}
