export enum BotTag {
  'anime' = 'Anime',
  'dashboard' = 'Dashboard',
  'diversao' = 'Diversão',
  'utilidades' = 'Utilidades',
  'social' = 'Social',
  'jogos' = 'Jogos',
  'musica' = 'Música',
  'moderacao' = 'Moderação',
  'economia' = 'Economia',
  'nsfw' = 'NSFW',
  'outros' = 'Outros'
}

export enum BotTagColor {
  'anime' = 'red',
  'dashboard' = 'darkorange',
  'diversao' = 'orange',
  'utilidades' = 'yellow',
  'social' = 'yellowgreen',
  'jogos' = 'green',
  'musica' = 'seagreen',
  'moderacao' = 'dodgerblue',
  'economia' = 'blue',
  'nsfw' = 'indigo',
  'outros' = 'purple'
}

export enum BotLibrary {
  'discord.js' = 'discord.js',
  'discord.py' = 'discord.py',
  'discordCr' = 'discordCr',
  'discord.io' = 'discord.io',
  'eris' = 'eris',
  'RestCord' = 'RestCord',
  'discordia' = 'discordia',
  'nxy' = 'nxy',
  'serenity' = 'serenity',
  'discordie' = 'discordie',
  'DiscordPHP' = 'DiscordPHP',
  'Sword' = 'Sword',
  'DiscordUnity' = 'DiscordUnity',
  'litcord' = 'litcord',
  'discord-hs' = 'discord-hs',
  'discordrb' = 'discordrb',
  'Discord.Net' = 'Discord.Net',
  'JDA' = 'JDA',
  'Javacord' = 'Javacord',
  'DSharpPlus' = 'DSharpPlus',
  'dscord' = 'dscord',
  'DiscordGo' = 'DiscordGo',
  'DisGord' = 'DisGord',
  'Discord4j' = 'Discord4j',
  'discordnim' = 'discordnim',
  'Yasmin' = 'Yasmin',
  'Disco' = 'disco',
  'AckCord' = 'AckCord',
  'Bot Designer' = 'Bot Designer',
  'DBM' = 'DBM',
  'Outro' = 'Outro'
}
